apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: application3-image-policy
  namespace: default
spec:
  imageRepositoryRef:
    name: application3-repository  # Matches your ImageRepository
  policy:
    alphabetical:
      order: asc  # Picks the lexicographically last tag (e.g., latest)
