apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmChart
metadata:
  name: application4-chart
  namespace: flux-system
spec:
  chart: charts
  sourceRef:
    kind: GitRepository
    name: application4-repo  # Matches GitRepository
  interval: 5m
